In [1]:
import pandas as pd
import os
%matplotlib widget
import numpy as np

In [7]:
names = ['J0023', 'J0136', 'J0020', 'J0203', 'J0243', 'J0333', 'J0404',
            'J2204', 'J2258', 'J2336', 'J0328']
DIR = '/Users/javieratoro/Desktop/thesis/proyecto 2024-2/'
path_emission = DIR + 'CSV_files/emission_line1.csv'
lines = pd.read_csv(path_emission)

auroral_lines = ['N2_5756', 'O1_6363',
                 'O3_4363', 'S3_6312',
                 'O2_7322', 'O2_7333', 'S2_4068', 'S2_4076']

bright_lines = ['O2_3725', 'O2_3727', 'H_alpha', 'H_beta',
                'H_gamma', 'O3_5008', 'O3_4959', 'N2_6550',
                'N2_6585', 'S2_6716', 'S2_6730']

for name in names:
    print(f'Saving for {name}')

    model = pd.read_csv(DIR + f'lines/{name}/{name}_iter_parts.csv')
    auroral = pd.read_csv(DIR + f'lines//{name}/{name}_auroral_iter_parts.csv')
    data = pd.read_csv(DIR + f'lines//{name}/{name}_model_parts.csv')

    df =  model.copy()


    for column in auroral.columns:
        if column[0] == 's':
            df[column + '_AU'] = auroral[column]

        df[column] = auroral[column]

    df.to_csv(DIR + f'lines/{name}_line_fluxes_parts.csv')

Saving for J0023
Saving for J0136
Saving for J0020
Saving for J0203
Saving for J0243
Saving for J0333
Saving for J0404
Saving for J2204
Saving for J2258
Saving for J2336
Saving for J0328

In [10]:
def save_fluxes_au():
    DIR = '/Users/javieratoro/Desktop/thesis/proyecto 2024-2/'
    lines = pd.read_csv(DIR + 'CSV_files/emission_line1.csv')

    names = ['J0023', 'J0136', 'J0020', 'J0203', 'J0243', 'J0333',
             'J0404','J2204', 'J2258', 'J2336', 'J0328']

    columns_ = ['ID', 'mass', 'z_red', 'z_blue']
    for line in lines['name']:
        columns_.append(line + '_flux')
        columns_.append(line + '_fluxerr')

    df = pd.DataFrame(columns=columns_)

    bright_lines = ['O2_3725', 'O2_3727', 'H_alpha', 'H_beta',
                    'H_gamma', 'O3_5008', 'O3_4959', 'N2_6550',
                    'N2_6585', 'S2_6716', 'S2_6730']

    auroral_lines = ['N2_5756', 'O1_6363',
                     'O3_4363', 'S3_6312',
                     'O2_7322', 'O2_7333',
                     'O2_7322_7333', 'S2_4068', 'S2_4076']

    for name in names:
        fluxes = pd.read_csv(DIR + f'lines/{name}_line_fluxes_parts.csv')
        data = pd.read_csv(DIR + f'lines/{name}/{name}_model_parts.csv')
        auroral = pd.read_csv(DIR +f'lines/{name}/{name}_auroral_model_parts.csv')
        all_rows = {'ID':data['ID'][0], 'mass':data['mass'][0],
                    'z_red':data['z_red'][0], "z_blue":data['z_blue'][0]}
        for line in lines['name']:
            if line in auroral_lines:
                print(line)
                flux = auroral[auroral['name']==line]['flux'].values[0]
                flux_err = auroral[auroral['name']==line]['fluxerr'].values[0]
                print(flux, flux_err)
                all_rows[line + '_flux'] = flux
                all_rows[line + '_fluxerr'] = flux_err
            else:
                narrow = fluxes[line + '_narrow'].values
                flux = narrow
                if line in bright_lines:
                    broad = fluxes[line + '_broad'].values
                    flux += broad
                all_rows[line + '_flux'] = np.median(flux)
                all_rows[line + '_fluxerr'] = np.std(flux)

        df.loc[-1] = all_rows
        df.index = df.index + 1
    df.to_csv(DIR + 'lines/magE2024_master_au_parts.csv')
    return df

In [22]:
name='J0020'
auroral = pd.read_csv(DIR +f'lines/{name}/{name}_auroral_model.csv')
auroral[auroral['name']=='S2_4068']['narrow_flux'], auroral

(7    0.000001
 Name: narrow_flux, dtype: float64,
    Unnamed: 0.2  Unnamed: 0.1  Unnamed: 0          ID  mass         z  \
 0             0           0.0         0.0  J0020+0030   9.6  0.105562
 1             1           1.0         1.0  J0020+0030   9.6  0.105562
 2             2           2.0         2.0  J0020+0030   9.6  0.105562
 3             3           3.0         3.0  J0020+0030   9.6  0.105562
 4             4           4.0         4.0  J0020+0030   9.6  0.105562
 5             5           5.0         5.0  J0020+0030   9.6  0.105562
 6             6           6.0         6.0  J0020+0030   9.6  0.105562
 7             7           NaN         NaN  J0020+0030   9.6  0.105562
 8             8           NaN         NaN  J0020+0030   9.6  0.105562

            name       flux   fluxerr  narrow_flux  narrow_fluxerr  \
 0       N2_5756   2.976099  0.474563     2.787659        0.486797
 1       O1_6363  14.973958  0.531548    10.624520        0.561504
 2       O3_4363   7.098363  0.613591     3.373614        0.867362
 3       S3_6312   8.370092  0.495203     4.298449        0.535738
 4       O2_7320  24.146890  0.848185     9.660768        0.833469
 5       O2_7331  14.828803  0.963139     9.326437        0.896849
 6  O2_7320_7331  39.172610  1.075406    19.186037        1.106405
 7       S2_4068   6.277249  0.404347     0.000001        0.575569
 8       S2_4076   0.274632  0.190847     0.274625        0.190847

      broad_flux  broad_fluxerr
 0  4.711861e-05       0.379322
 1  4.333343e+00       0.898878
 2  3.669863e+00       1.333801
 3  4.178389e+00       0.861915
 4  1.439036e+01       1.352585
 5  5.515140e+00       1.598515
 6  1.986109e+01       1.646873
 7  6.264061e+00       0.797136
 8  2.728306e-07       0.000003  )

In [11]:
save_fluxes_au()

S2_4068
10.036067421855233 0.8816264434267427
S2_4076
2.178176587429129 0.8448784757693331
O3_4363
59.63341015403569 1.0299617851263765
N2_5756
0.5860022877713769 0.466429795044386
S3_6312
16.849819925358176 0.4384294598404966
O1_6363
16.140380008970173 0.3797456278057741
S2_4068
8.8026651588227 1.7859933324590356
S2_4076
5.03035651598154 2.0783188077845987
O3_4363
85.44201736575724 1.8633844872264365
N2_5756
0.5749869679803126 0.6023683021652504
S3_6312
11.834499795177267 0.7491992667248707
O1_6363
7.342627384563641 0.6744983544076597
S2_4068
6.614312211398019 0.4116269039263239
S2_4076
8.708467751193973e-08 0.1089319650399495
O3_4363
6.8454410670443115 0.3876973815760778
N2_5756
3.679892416647302 0.4521905619908855
S3_6312
8.601745776586528 0.3875182830410489
O1_6363
17.540751450779307 0.4318555582990072
S2_4068
2.552568633012906 0.3148693677918047
S2_4076
8.114768334725141e-07 0.1030739217154671
O3_4363
2.295438635873051 0.2892016474527842
N2_5756
0.9001400377849575 0.2784061410844228
S3_6312
0.5821814107529064 0.3150789738606243
O1_6363
1.913117694213164 0.4011704376009513
S2_4068
5.257472256587749 0.7782237293586463
S2_4076
0.6096579573684893 0.5870531172726949
O3_4363
21.815246176688483 0.6060307664206545
N2_5756
2.689257780405294 0.5986381781721359
S3_6312
10.243683985058674 0.627183797889776
O1_6363
8.286228456598458 0.5872241752571518
S2_4068
9.738313060604654 0.5078904677290834
S2_4076
1.9043539455674392 0.6665393793558158
O3_4363
43.70592574351565 0.5641340440356517
N2_5756
4.84317607789238 0.5291796692540647
S3_6312
17.029519603182298 0.5251412937194007
O1_6363
24.52193466378813 3.0148181749860465
S2_4068
2.363357092472108 0.5567356939101058
S2_4076
2.887879506806153e-10 3.0755683212639234e-05
O3_4363
6.052588374365876 0.5154365878154339
N2_5756
5.049530431977604e-12 0.294663437185222
S3_6312
3.127228812707522 0.3883599427853819
O1_6363
10.020188643507584 17.226795636865024
S2_4068
4.217521916035343 0.3626409217455174
S2_4076
1.5006092604456122e-09 0.0066538215454796
O3_4363
8.635519625990813 0.3317723257004716
N2_5756
1.7241067677974642 0.305169238731793
S3_6312
2.7266413682536084 0.5215121168581407
O1_6363
6.331746890180426 0.3975912896564643
S2_4068
4.843599474268793 0.4896260263251586
S2_4076
0.6225837682983641 0.4151321907212503
O3_4363
18.6771630281118 0.5274010483936601
N2_5756
0.6327113554090419 0.2262905196725716
S3_6312
4.058282769238119 0.2132071538535311
O1_6363
3.2772260027959517 0.1890562101214812
S2_4068
3.23010646080541 0.3195458286969523
S2_4076
0.9189607300327036 0.2782752312423733
O3_4363
6.633478325169336 0.2627720802633731
N2_5756
1.2358655554377245 0.2262039388208407
S3_6312
4.270836836915237 0.3333506426254371
O1_6363
6.106725740399414 0.340867090320344
S2_4068
11.776330477663304 0.8081105134620491
S2_4076
4.413698141916475e-08 0.1732775215145807
O3_4363
13.37764899836747 0.7534177065853463
N2_5756
5.788479556232448 0.6197156588783685
S3_6312
11.87444509314492 0.5756800820690182
O1_6363
25.73884903954424 0.6710875810009771

,ID,mass,z_red,z_blue,H_14_flux,H_14_fluxerr,O2_3725_flux,O2_3725_fluxerr,O2_3727_flux,O2_3727_fluxerr,...,O2_7320_flux,O2_7320_fluxerr,O2_7331_flux,O2_7331_fluxerr,Ni2_7380_flux,Ni2_7380_fluxerr,Ni2_7414_flux,Ni2_7414_fluxerr,Ar3_7751_flux,Ar3_7751_fluxerr
10,J0023-0948,8.90,0.053081,0.053060,18.769557,1.078604,543.114185,4.957113,744.134356,3.109997,...,26.150604,0.656191,23.988130,0.894189,1.417942,0.401636,0.009624,0.112878,23.211876,0.814328
9,J0136-0037,9.10,0.059445,0.059425,15.533470,4.771781,393.903868,5.979897,555.675645,6.311955,...,9.773207,0.830174,8.191390,0.746197,0.000286,0.103442,8.494838,1.616051,9.095718,1.168606
8,J0020+0030,9.60,0.105580,0.105593,3.514797,0.720869,320.641047,14.824326,335.446135,9.866272,...,9.090072,0.369302,6.663875,0.286968,1.304920,0.193647,0.897023,0.219873,4.295147,0.201902
7,J0203+0035,9.96,0.156161,0.156164,0.000001,0.071118,95.253618,1.021990,84.984007,0.925789,...,3.392448,0.453470,3.552830,0.253573,1.221070,0.190963,0.245819,0.163152,0.000018,0.000046
6,J0243+0111,9.70,0.134388,0.134350,1.194318,4.319040,231.006263,5.244470,410.874883,3.654369,...,10.393229,0.649926,9.672393,0.624034,1.604580,0.546805,1.329792,0.428723,7.332463,0.482156
5,J0333+0017,9.90,0.193823,0.193848,0.000887,0.003229,432.090781,2.234852,519.493845,2.329213,...,18.201882,0.583654,15.136898,0.479328,4.103325,0.303081,2.893322,0.422544,14.432920,0.609407
4,J0404+0538,10.20,0.065799,0.065823,2.387415,0.795615,128.448596,1.937320,133.067276,1.778561,...,2.711666,0.261127,2.283986,0.296432,1.068325,0.246552,0.000009,0.000811,2.238686,0.333189
3,J2204+0058,10.16,0.184998,0.185020,2.705171,1.002885,128.024201,1.968821,228.322432,1.613661,...,5.222000,0.423776,3.651690,0.289470,1.146424,0.252839,2.473407,0.358679,1.059481,0.317209
2,J2258+0056,9.60,0.094026,0.094035,2.038575,0.385574,94.107422,6.950716,112.648714,5.002043,...,4.824997,0.247513,4.338637,0.262964,0.100009,0.154230,0.000111,0.015247,3.279428,0.231172
1,J2336-0042,9.90,0.170525,0.170510,0.894139,0.701979,201.459863,1.126870,233.758739,1.393944,...,8.619177,0.289849,6.436615,0.275867,0.000770,0.184556,0.000274,0.143059,8.898685,0.347168
0,J0328+0031,9.80,0.085838,0.085858,3.186424,3.206063,544.694741,5.933615,656.053270,3.854004,...,24.343488,0.586020,21.194746,0.584344,3.780618,0.492860,0.000170,0.001244,5.641719,1.169350

In [12]:
def save_fluxes_or():
    DIR = '/Users/javieratoro/Desktop/thesis/proyecto 2024-2/'
    lines = pd.read_csv(DIR + 'CSV_files/emission_line1.csv')

    names = ['J0023', 'J0136', 'J0020', 'J0203', 'J0243', 'J0333',
             'J0404', 'J2204', 'J2258', 'J2336', 'J0328']

    columns_ = ['ID', 'mass', 'z_red', 'z_blue']
    for line in lines['name']:
        columns_.append(line + '_flux')
        columns_.append(line + '_fluxerr')

    df = pd.DataFrame(columns=columns_)

    bright_lines = ['O2_3725', 'O2_3727', 'H_alpha', 'H_beta',
                    'H_gamma', 'O3_5008', 'O3_4959', 'N2_6550',
                    'N2_6585', 'S2_6716', 'S2_6730']


    for name in names:
        all_rows = {'ID':name}
        fluxes = pd.read_csv(DIR + f'lines/{name}_line_fluxes_parts.csv')
        data = pd.read_csv(DIR + f'lines/{name}/{name}_model_parts.csv')
        all_rows = {'ID':data['ID'][0], 'mass':data['mass'][0],
                    'z_red':data['z_red'][0], "z_blue":data['z_blue'][0]}
        for line in lines['name']:
            narrow = fluxes[line + '_narrow'].values
            flux = narrow
            if line in bright_lines:
                broad = fluxes[line + '_broad'].values
                flux += broad

            all_rows[line + '_flux'] = np.median(flux)
            all_rows[line + '_fluxerr'] = np.std(flux)

        df.loc[-1] = all_rows
        df.index = df.index + 1
    df.to_csv(DIR + 'lines/magE2024_master_or_parts.csv')
    return df

In [13]:
save_fluxes_or()

,ID,mass,z_red,z_blue,H_14_flux,H_14_fluxerr,O2_3725_flux,O2_3725_fluxerr,O2_3727_flux,O2_3727_fluxerr,...,O2_7320_flux,O2_7320_fluxerr,O2_7331_flux,O2_7331_fluxerr,Ni2_7380_flux,Ni2_7380_fluxerr,Ni2_7414_flux,Ni2_7414_fluxerr,Ar3_7751_flux,Ar3_7751_fluxerr
10,J0023-0948,8.90,0.053081,0.053060,18.769557,1.078604,543.114185,4.957113,744.134356,3.109997,...,26.150604,0.656191,23.988130,0.894189,1.417942,0.401636,0.009624,0.112878,23.211876,0.814328
9,J0136-0037,9.10,0.059445,0.059425,15.533470,4.771781,393.903868,5.979897,555.675645,6.311955,...,9.773207,0.830174,8.191390,0.746197,0.000286,0.103442,8.494838,1.616051,9.095718,1.168606
8,J0020+0030,9.60,0.105580,0.105593,3.514797,0.720869,320.641047,14.824326,335.446135,9.866272,...,9.090072,0.369302,6.663875,0.286968,1.304920,0.193647,0.897023,0.219873,4.295147,0.201902
7,J0203+0035,9.96,0.156161,0.156164,0.000001,0.071118,95.253618,1.021990,84.984007,0.925789,...,3.392448,0.453470,3.552830,0.253573,1.221070,0.190963,0.245819,0.163152,0.000018,0.000046
6,J0243+0111,9.70,0.134388,0.134350,1.194318,4.319040,231.006263,5.244470,410.874883,3.654369,...,10.393229,0.649926,9.672393,0.624034,1.604580,0.546805,1.329792,0.428723,7.332463,0.482156
5,J0333+0017,9.90,0.193823,0.193848,0.000887,0.003229,432.090781,2.234852,519.493845,2.329213,...,18.201882,0.583654,15.136898,0.479328,4.103325,0.303081,2.893322,0.422544,14.432920,0.609407
4,J0404+0538,10.20,0.065799,0.065823,2.387415,0.795615,128.448596,1.937320,133.067276,1.778561,...,2.711666,0.261127,2.283986,0.296432,1.068325,0.246552,0.000009,0.000811,2.238686,0.333189
3,J2204+0058,10.16,0.184998,0.185020,2.705171,1.002885,128.024201,1.968821,228.322432,1.613661,...,5.222000,0.423776,3.651690,0.289470,1.146424,0.252839,2.473407,0.358679,1.059481,0.317209
2,J2258+0056,9.60,0.094026,0.094035,2.038575,0.385574,94.107422,6.950716,112.648714,5.002043,...,4.824997,0.247513,4.338637,0.262964,0.100009,0.154230,0.000111,0.015247,3.279428,0.231172
1,J2336-0042,9.90,0.170525,0.170510,0.894139,0.701979,201.459863,1.126870,233.758739,1.393944,...,8.619177,0.289849,6.436615,0.275867,0.000770,0.184556,0.000274,0.143059,8.898685,0.347168
0,J0328+0031,9.80,0.085838,0.085858,3.186424,3.206063,544.694741,5.933615,656.053270,3.854004,...,24.343488,0.586020,21.194746,0.584344,3.780618,0.492860,0.000170,0.001244,5.641719,1.169350

In [36]:
    DIR = '/Users/javieratoro/Desktop/thesis/proyecto 2024-2/'
    lines = pd.read_csv(DIR + 'CSV_files/emission_line1.csv')
    lines_h_fluxes = pd.read_csv(DIR + 'lines/EW_CORR_H_FLUXES.csv')

In [41]:
lines_h_fluxes[lines_h_fluxes['ID'] == 'J0020+0030']['H_alpha_flux'].values

array([3040.6078685])